modLoader = "javafml"
loaderVersion = "[${forge_loader_version_range},)"

license = "${mod_license}"
issueTrackerURL = "https://github.com/TeamFossilsArcheology/FossilsArcheologyRevival/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/fossils"

logoFile = "fossils.png"
credits = "Original mod by Flammarilva and Team July!"
authors = "${forge_mod_authors}"
description = "${mod_description}"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version_range},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version_range_lower},${minecraft_version_range_upper})"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "architectury"
mandatory = true
versionRange = "[9.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "geckolib"
mandatory = true
versionRange = "[4.4.7,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "roughlyenoughitems"
mandatory = false
versionRange = "[12,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "terrablender"
mandatory = true
versionRange = "[3,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "morehitboxes"
mandatory = true
versionRange = "[1.9.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "carryon"
mandatory = false
versionRange = "[2.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "farmers-delight"
mandatory = false
versionRange = "[1.2.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "argentinas_delight"
mandatory = false
versionRange = "[1.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "culturaldelights"
mandatory = false
versionRange = "[0.16.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "crabbersdelight"
mandatory = false
versionRange = "[1.2.2,)"
ordering = "NONE"
side = "BOTH"

[modproperties.${mod_id}]
catalogueImageIcon="fossils.png"